// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeventhServices.QQRobot.Resource;

namespace SeventhServices.QQRobot.Resource.Migrations
{
    [DbContext(typeof(QBotDbContext))]
    partial class QBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0-preview3.19554.8");

            modelBuilder.Entity("SeventhServices.QQRobot.Resource.Entities.AccountBinding", b =>
                {
                    b.Property<string>("BoundAccountPid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qq")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BindTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPidOnly")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoundAccountPid", "Qq");

                    b.ToTable("AccountBindings");
                });

            modelBuilder.Entity("SeventhServices.QQRobot.Resource.Entities.BoundAccount", b =>
                {
                    b.Property<string>("Pid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qq")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncPid")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ivs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tpid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Pid", "Qq");

                    b.ToTable("BoundAccounts");
                });

            modelBuilder.Entity("SeventhServices.QQRobot.Resource.Entities.BoundAccount", b =>
                {
                    b.HasOne("SeventhServices.QQRobot.Resource.Entities.AccountBinding", "AccountBinding")
                        .WithOne("BoundAccount")
                        .HasForeignKey("SeventhServices.QQRobot.Resource.Entities.BoundAccount", "Pid", "Qq")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
